# Generated by Django 4.1.5 on 2023-02-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=70)),
                ('vaqt', models.DateField()),
                ('batafsil', models.TextField()),
                ('holat', models.CharField(choices=[('bajarildi', 'bajarildi'), ('bajarilmoqda', 'bajarilmoqda'), ('bajarilmadi', 'bajarilmadi')], max_length=20)),
            ],
        ),
    ]
