# Generated by Django 4.1.5 on 2023-02-16 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_talaba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='foydalanuvchi',
        ),
        migrations.AddField(
            model_name='todo',
            name='talaba',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asosiy.talaba'),
        ),
    ]
